// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: events.sql

package repository

import (
	"context"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    "type", entity_type, entity_id, event_data
) VALUES (
    $1, $2, $3, $3
 )
RETURNING id, type, entity_type, entity_id, event_data, created_at
`

type CreateEventParams struct {
	Type       string
	EntityType string
	EntityID   int32
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent, arg.Type, arg.EntityType, arg.EntityID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.EntityType,
		&i.EntityID,
		&i.EventData,
		&i.CreatedAt,
	)
	return i, err
}
