// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/tabbed/pqtype"
)

type Event struct {
	ID         int32
	Type       string
	EntityType string
	EntityID   int32
	EventData  json.RawMessage
	CreatedAt  time.Time
}

type Outbox struct {
	EventID       int32
	EventType     string
	AggregateType string
	AggregateID   string
	Payload       pqtype.NullRawMessage
	CreatedAt     sql.NullTime
}
