// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/tabbed/pqtype"
)

type Outbox struct {
	EventID       uuid.UUID
	EventType     string
	AggregateType string
	AggregateID   string
	Payload       pqtype.NullRawMessage
	CreatedAt     sql.NullTime
}
