// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Outbox, error)
	DeleteEvents(ctx context.Context, eventIds []uuid.UUID) error
	ListEvents(ctx context.Context) ([]Outbox, error)
}

var _ Querier = (*Queries)(nil)
