// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import (
	"context"
)

type Querier interface {
	AddToOutbox(ctx context.Context, arg AddToOutboxParams) (Outbox, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	DeleteFromOutbox(ctx context.Context, eventIds []int32) error
	ListOutbox(ctx context.Context) ([]Outbox, error)
}

var _ Querier = (*Queries)(nil)
