apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-relay
  labels:
    app: message-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-relay
  template:
    metadata:
      labels:
        app: message-relay
    spec:
      containers:
        - name: message-relay
          image: emmanuelperotto/msgrelay
          imagePullPolicy: Never
#    metadata:
#      labels:
#        app: nginx
#    spec:
#      containers:
#        - name: nginx
#          image: nginx:1.14.2
#          ports:
#            - containerPort: 80